import json
from pathlib import Path

from caelestia.utils.paths import atomic_write


def apply_vscode(colours: dict[str, str], mode: str) -> None:
    vscode_settings = Path("~/.config/Code/User/settings.json").expanduser()

    try:
        settings = json.loads(vscode_settings.read_text())
    except (OSError, json.JSONDecodeError):
        settings = {}

    settings["workbench.colorCustomizations"] = _gen_workbench(colours)
    settings["editor.tokenColorCustomizations"] = _gen_token_colors(colours)

    settings["window.autoDetectColorScheme"] = False
    settings["window.autoDetectHighContrast"] = False

    atomic_write(vscode_settings, json.dumps(settings, indent=4))


def _gen_workbench(c: dict[str, str]) -> dict[str, str]:
    def h(key: str, fallback: str = "000000") -> str:
        return f"#{c.get(key, fallback)}"

    def halpha(key: str, alpha: str, fallback: str = "000000") -> str:
        return f"#{c.get(key, fallback)}{alpha}"

    return {
        "editor.background": h("surface"),
        "editor.foreground": h("onSurface"),
        "editor.lineHighlightBackground": halpha("surfaceContainerHigh", "60"),
        "editor.selectionBackground": halpha("primary", "30"),
        "editor.selectionHighlightBackground": halpha("primary", "15"),
        "editor.wordHighlightBackground": halpha("primary", "20"),
        "editor.wordHighlightStrongBackground": halpha("primary", "30"),
        "editor.findMatchBackground": halpha("yellow", "40"),
        "editor.findMatchHighlightBackground": halpha("yellow", "20"),
        "editor.findMatchBorder": h("yellow"),
        "editorCursor.foreground": h("primary"),
        "editorWhitespace.foreground": halpha("outlineVariant", "40"),
        "editorIndentGuide.background": halpha("outlineVariant", "30"),
        "editorIndentGuide.activeBackground": halpha("outlineVariant", "60"),
        "editorLineNumber.foreground": h("onSurfaceVariant"),
        "editorLineNumber.activeForeground": h("onSurface"),
        "editorBracketMatch.background": halpha("primary", "20"),
        "editorBracketMatch.border": halpha("primary", "50"),
        "editorGutter.background": h("surface"),
        "editorWidget.background": h("surfaceContainerHigh"),
        "editorWidget.foreground": h("onSurface"),
        "editorWidget.border": halpha("outlineVariant", "40"),
        "editorSuggestWidget.background": h("surfaceContainerHigh"),
        "editorSuggestWidget.border": halpha("outlineVariant", "40"),
        "editorSuggestWidget.selectedBackground": halpha("primary", "20"),
        "editorSuggestWidget.highlightForeground": h("primary"),
        "editorHoverWidget.background": h("surfaceContainerHigh"),
        "editorHoverWidget.border": halpha("outlineVariant", "40"),
        "editorError.foreground": h("error"),
        "editorWarning.foreground": h("yellow"),
        "editorInfo.foreground": h("blue"),
        "editorHint.foreground": h("success"),
        "activityBar.background": h("surface"),
        "activityBar.foreground": h("onSurface"),
        "activityBar.activeBorder": h("primary"),
        "activityBar.activeBackground": halpha("primary", "15"),
        "activityBar.border": halpha("outlineVariant", "30"),
        "activityBarBadge.background": h("primary"),
        "activityBarBadge.foreground": h("onPrimary"),
        "sideBar.background": h("surface"),
        "sideBar.foreground": h("onSurface"),
        "sideBar.border": halpha("outlineVariant", "30"),
        "sideBarTitle.foreground": h("onSurface"),
        "sideBarSectionHeader.background": h("surfaceContainer"),
        "sideBarSectionHeader.foreground": h("onSurfaceVariant"),
        "sideBarSectionHeader.border": halpha("outlineVariant", "30"),
        "list.activeSelectionBackground": halpha("primary", "20"),
        "list.activeSelectionForeground": h("onSurface"),
        "list.activeSelectionIconForeground": h("onSurface"),
        "list.inactiveSelectionBackground": halpha("primary", "10"),
        "list.inactiveSelectionForeground": h("onSurface"),
        "list.hoverBackground": halpha("outlineVariant", "20"),
        "list.hoverForeground": h("onSurface"),
        "list.focusBackground": halpha("primary", "15"),
        "list.focusForeground": h("onSurface"),
        "list.highlightForeground": h("primary"),
        "listFilterMatch.background": halpha("primary", "30"),
        "listFilterMatch.border": h("primary"),
        "tree.indentGuidesStroke": halpha("outlineVariant", "30"),
        "menu.background": h("surfaceContainerHigh"),
        "menu.foreground": h("onSurface"),
        "menu.selectionBackground": halpha("primary", "20"),
        "menu.selectionForeground": h("onSurface"),
        "menu.separatorBackground": halpha("outlineVariant", "40"),
        "menu.border": halpha("outlineVariant", "40"),
        "input.background": h("surfaceContainer"),
        "input.foreground": h("onSurface"),
        "input.border": halpha("outlineVariant", "40"),
        "input.placeholderForeground": h("outline"),
        "inputOption.activeBorder": h("primary"),
        "inputOption.activeBackground": halpha("primary", "20"),
        "inputValidation.errorBackground": halpha("error", "20"),
        "inputValidation.errorBorder": h("error"),
        "inputValidation.warningBackground": halpha("yellow", "20"),
        "inputValidation.warningBorder": h("yellow"),
        "dropdown.background": h("surfaceContainerHigh"),
        "dropdown.foreground": h("onSurface"),
        "dropdown.border": halpha("outlineVariant", "40"),
        "button.background": h("primary"),
        "button.foreground": h("onPrimary"),
        "button.hoverBackground": h("primaryFixedDim"),
        "button.secondaryBackground": h("secondaryContainer"),
        "button.secondaryForeground": h("onSecondaryContainer"),
        "button.secondaryHoverBackground": h("secondaryFixedDim"),
        "badge.background": h("primary"),
        "badge.foreground": h("onPrimary"),
        "scrollbar.shadow": "#00000000",
        "scrollbarSlider.background": halpha("outlineVariant", "30"),
        "scrollbarSlider.hoverBackground": halpha("outlineVariant", "60"),
        "scrollbarSlider.activeBackground": halpha("outline", "55"),
        "scrollbarSlider.border": "#00000000",
        "progressBar.background": h("primary"),
        "panels.background": h("surface"),
        "panels.border": halpha("outlineVariant", "30"),
        "panelsTitle.border": halpha("outlineVariant", "30"),
        "tab.activeBackground": h("surfaceContainerHigh"),
        "tab.activeForeground": h("onSurface"),
        "tab.activeBorder": h("primary"),
        "tab.activeBorderTop": "#00000000",
        "tab.inactiveBackground": h("surface"),
        "tab.inactiveForeground": h("onSurfaceVariant"),
        "tab.hoverBackground": h("surfaceContainer"),
        "tab.border": halpha("outlineVariant", "30"),
        "tab.unfocusedActiveBackground": h("surfaceContainerHigh"),
        "tab.unfocusedActiveForeground": h("onSurfaceVariant"),
        "tab.unfocusedInactiveBackground": h("surface"),
        "tab.unfocusedInactiveForeground": h("onSurfaceVariant"),
        "breadcrumb.foreground": h("onSurfaceVariant"),
        "breadcrumb.focusForeground": h("onSurface"),
        "breadcrumb.activeSelectionForeground": h("primary"),
        "breadcrumbPicker.background": h("surfaceContainerHigh"),
        "titleBar.activeBackground": h("surface"),
        "titleBar.activeForeground": h("onSurface"),
        "titleBar.inactiveBackground": h("surface"),
        "titleBar.inactiveForeground": h("onSurfaceVariant"),
        "titleBar.border": halpha("outlineVariant", "30"),
        "statusBar.background": h("surface"),
        "statusBar.foreground": h("onSurface"),
        "statusBar.border": halpha("outlineVariant", "30"),
        "statusBar.debuggingBackground": h("yellow"),
        "statusBar.debuggingForeground": h("onSurface"),
        "statusBar.noFolderBackground": h("surfaceContainer"),
        "statusBar.noFolderForeground": h("onSurface"),
        "commandCenter.foreground": h("onSurface"),
        "commandCenter.activeForeground": h("onSurface"),
        "commandCenter.background": h("surfaceContainer"),
        "commandCenter.activeBackground": h("surfaceContainerHigh"),
        "commandCenter.border": halpha("outlineVariant", "40"),
        "commandCenter.activeBorder": halpha("outlineVariant", "60"),
        "notificationCenter.border": halpha("outlineVariant", "40"),
        "notificationCenterHeader.background": h("surfaceContainerHigh"),
        "notificationCenterHeader.foreground": h("onSurface"),
        "notifications.background": h("surfaceContainerHigh"),
        "notifications.foreground": h("onSurface"),
        "notifications.border": halpha("outlineVariant", "40"),
        "notificationLink.foreground": h("primary"),
        "notificationsErrorIcon.foreground": h("error"),
        "notificationsWarningIcon.foreground": h("yellow"),
        "notificationsInfoIcon.foreground": h("blue"),
        "pickerGroup.foreground": h("primary"),
        "pickerGroup.border": halpha("outlineVariant", "40"),
        "keybindingLabel.background": h("surfaceContainer"),
        "keybindingLabel.foreground": h("onSurface"),
        "keybindingLabel.border": halpha("outlineVariant", "40"),
        "keybindingLabel.bottomBorder": halpha("outlineVariant", "60"),
        "keybindingTable.headerBackground": h("surfaceContainer"),
        "keybindingTable.headerForeground": h("onSurface"),
        "keybindingTable.rowBackground": h("surface"),
        "keybindingTable.rowHoverBackground": halpha("outlineVariant", "20"),
        "keybindingTable.separator": halpha("outlineVariant", "30"),
        "terminal.background": h("surface"),
        "terminal.foreground": h("onSurface"),
        "terminal.ansiBlack": h("term0"),
        "terminal.ansiRed": h("term1"),
        "terminal.ansiGreen": h("term2"),
        "terminal.ansiYellow": h("term3"),
        "terminal.ansiBlue": h("term4"),
        "terminal.ansiMagenta": h("term5"),
        "terminal.ansiCyan": h("term6"),
        "terminal.ansiWhite": h("term7"),
        "terminal.ansiBrightBlack": h("term8"),
        "terminal.ansiBrightRed": h("term9"),
        "terminal.ansiBrightGreen": h("term10"),
        "terminal.ansiBrightYellow": h("term11"),
        "terminal.ansiBrightBlue": h("term12"),
        "terminal.ansiBrightMagenta": h("term13"),
        "terminal.ansiBrightCyan": h("term14"),
        "terminal.ansiBrightWhite": h("term15"),
        "terminal.selectionBackground": halpha("primary", "30"),
        "terminalCursor.foreground": h("primary"),
        "terminal.border": halpha("outlineVariant", "30"),
        "minimap.background": h("surface"),
        "minimap.selectionHighlight": halpha("primary", "30"),
        "minimap.findMatchHighlight": halpha("yellow", "40"),
        "minimap.errorHighlight": halpha("error", "40"),
        "minimap.warningHighlight": halpha("yellow", "40"),
        "minimapSlider.background": halpha("outlineVariant", "15"),
        "minimapSlider.hoverBackground": halpha("outlineVariant", "25"),
        "minimapSlider.activeBackground": halpha("outlineVariant", "35"),
        "minimapSlider.border": halpha("outlineVariant", "30"),
        "diffEditor.insertedTextBackground": halpha("green", "20"),
        "diffEditor.removedTextBackground": halpha("red", "20"),
        "diffEditor.insertedLineBackground": halpha("green", "10"),
        "diffEditor.removedLineBackground": halpha("red", "10"),
        "diffEditor.border": halpha("outlineVariant", "30"),
        "editorOverviewRuler.border": "#00000000",
        "editorOverviewRuler.findMatchForeground": halpha("yellow", "60"),
        "editorOverviewRuler.errorForeground": h("error"),
        "editorOverviewRuler.warningForeground": h("yellow"),
        "editorOverviewRuler.infoForeground": h("blue"),
        "editorOverviewRuler.bracketMatchForeground": halpha("primary", "40"),
        "peekView.border": h("primary"),
        "peekViewEditor.background": h("surfaceContainer"),
        "peekViewResult.background": h("surfaceContainerHigh"),
        "peekViewTitle.background": h("surfaceContainerHigh"),
        "peekViewResult.selectionBackground": halpha("primary", "20"),
        "peekViewEditor.selectionBackground": halpha("primary", "15"),
        "peekViewResult.fileForeground": h("onSurface"),
        "peekViewResult.lineForeground": h("onSurfaceVariant"),
        "peekViewResult.matchHighlightBackground": halpha("yellow", "40"),
        "peekViewResult.selectionForeground": h("onSurface"),
        "peekViewResult.selectionLineForeground": h("onSurface"),
        "peekViewEditor.matchHighlightBackground": halpha("yellow", "30"),
        "peekViewEditorGutter.background": h("surfaceContainer"),
        "peekViewTitleDescription.foreground": h("onSurfaceVariant"),
        "peekViewTitleLabel.foreground": h("onSurface"),
        "gitDecoration.addedResourceForeground": h("green"),
        "gitDecoration.modifiedResourceForeground": h("blue"),
        "gitDecoration.deletedResourceForeground": h("red"),
        "gitDecoration.renamedResourceForeground": h("teal"),
        "gitDecoration.stageModifiedResourceForeground": h("blue"),
        "gitDecoration.stageDeletedResourceForeground": h("red"),
        "gitDecoration.untrackedResourceForeground": h("green"),
        "gitDecoration.ignoredResourceForeground": h("onSurfaceVariant"),
        "gitDecoration.conflictingResourceForeground": h("yellow"),
        "gitDecoration.submoduleResourceForeground": h("onSurfaceVariant"),
        "searchEditor.findMatchBackground": halpha("yellow", "20"),
        "searchEditor.findMatchBorder": h("yellow"),
        "search.resultsInfoForeground": h("onSurfaceVariant"),
        "widget.shadow": "#00000040",
        "widget.border": halpha("outlineVariant", "40"),
        "widget.foreground": h("onSurface"),
        "widget.background": h("surfaceContainerHigh"),
        "widget.sortFilterToggle.background": halpha("primary", "20"),
        "widget.sortFilterToggle.foreground": h("onSurface"),
        "selection.background": halpha("primary", "30"),
        "textLink.foreground": h("primary"),
        "textLink.activeForeground": h("primaryFixedDim"),
        "textBlockQuote.background": h("surfaceContainer"),
        "textBlockQuote.border": h("primary"),
        "textCodeBlock.background": h("surfaceContainer"),
        "textPreformat.foreground": h("onSurface"),
        "textSeparator.foreground": h("outlineVariant"),
        "walkThrough.embeddedEditorBackground": h("surfaceContainer"),
    }


def _gen_token_colors(c: dict[str, str]) -> dict:
    def h(key: str, fallback: str = "000000") -> str:
        return f"#{c.get(key, fallback)}"

    return {
        "comments": {"foreground": h("subtext0"), "fontStyle": "italic"},
        "strings": {"foreground": h("green")},
        "keywords": {"foreground": h("pink")},
        "numbers": {"foreground": h("peach")},
        "regexp": {"foreground": h("sky")},
        "type": {"foreground": h("yellow")},
        "class": {"foreground": h("yellow")},
        "function": {"foreground": h("blue")},
        "function.declaration": {"foreground": h("blue")},
        "variable": {"foreground": h("onSurface")},
        "variable.parameter": {"foreground": h("teal"), "fontStyle": "italic"},
        "variable.predefined": {"foreground": h("onSurface"), "fontStyle": "italic"},
        "property": {"foreground": h("teal")},
        "constant": {"foreground": h("peach")},
        "annotation": {"foreground": h("yellow")},
        "operator": {"foreground": h("sapphire")},
        "namespace": {"foreground": h("teal")},
        "enum": {"foreground": h("yellow")},
        "enumMember": {"foreground": h("peach")},
        "struct": {"foreground": h("yellow")},
        "parameter": {"foreground": h("teal"), "fontStyle": "italic"},
        "typeParameter": {"foreground": h("teal"), "fontStyle": "italic"},
        "decorator": {"foreground": h("mauve")},
        "tag": {"foreground": h("yellow")},
        "attribute.name": {"foreground": h("yellow")},
        "attribute.value": {"foreground": h("green")},
        "metatag": {"foreground": h("mauve")},
        "metatag.content.html": {"foreground": h("green")},
        "metatag.html": {"foreground": h("mauve")},
        "metatag.php": {"foreground": h("mauve")},
        "key": {"foreground": h("blue")},
        "key.json": {"foreground": h("blue")},
        "string.key.json": {"foreground": h("blue")},
        "string.value.json": {"foreground": h("green")},
        "markup.heading": {"foreground": h("blue"), "fontStyle": "bold"},
        "markup.italic": {"fontStyle": "italic"},
        "markup.bold": {"fontStyle": "bold"},
        "markup.underline": {"fontStyle": "underline"},
        "markup.deleted": {"foreground": h("red")},
        "markup.inserted": {"foreground": h("green")},
        "markup.changed": {"foreground": h("yellow")},
        "markup.ignored": {"foreground": h("onSurfaceVariant")},
        "entity.name.tag": {"foreground": h("yellow")},
        "entity.other.attribute-name": {"foreground": h("yellow")},
        "entity.name.namespace": {"foreground": h("teal")},
        "entity.name.type": {"foreground": h("yellow")},
        "entity.other.inherited-class": {"foreground": h("yellow")},
        "entity.name.function": {"foreground": h("blue")},
        "entity.name.variable": {"foreground": h("onSurface")},
        "entity.name.constant": {"foreground": h("peach")},
        "entity.name.label": {"foreground": h("yellow")},
        "entity.name.section": {"foreground": h("blue")},
        "punctuation.definition.comment": {"foreground": h("subtext0"), "fontStyle": "italic"},
        "punctuation.definition.string": {"foreground": h("green")},
        "punctuation.definition.keyword": {"foreground": h("pink")},
        "punctuation.definition.variable": {"foreground": h("onSurface")},
        "punctuation.definition.parameters": {"foreground": h("onSurface")},
        "punctuation.separator": {"foreground": h("onSurface")},
        "punctuation.terminator": {"foreground": h("onSurface")},
    }
